#!/bin/bash

echo $$   # echo my pid

./p5 &

pid=$!   # get child pid
echo "PID" $pid

sleep 2
/bin/kill -USR1 $pid

sleep 2
/bin/kill -INT $pid

sleep 2
/bin/kill -USR1 $pid

sleep 2
/bin/kill -INT $pid

echo
/bin/kill -USR2 $pid

echo
pwd
